name: notes
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  flutter_switch: ^0.3.2
  google_fonts: ^6.2.1
  crop_your_image: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/splash/
    - assets/logo/
    - assets/add-note-bg/


